In [1]:
import numpy as np
from PIL import Image

In [2]:
array = np.zeros((100, 200, 3))

In [3]:
array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [4]:
img = Image.fromarray(array, 'RGB')

In [5]:
img.save('img.png')

In [6]:
img.show()

In [7]:
# for i in range(100):
#     for j in range(100):
#         array[i][j] = [150, 150, 150]

In [8]:
# img = Image.fromarray(array, 'RGB')

In [9]:
# img.save('img.png')

In [10]:
# img = Image.open("img.png")
# img.format
# img.size

In [11]:
data = np.asarray(img)

In [12]:
data

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [13]:
len(data)

100

In [14]:
i = 0
for i in range(100):
    for j in range(100):
        for k in range(3):
            i+=1
i            

399

In [15]:
row = 40
col = 40
for row in range(60):
    for col in range(60):
        array[row][col] = (255, 0, 0)

In [16]:
img2 = Image.fromarray(array, 'RGB')

In [17]:
img2.save("img2.png")
img2.show()

In [18]:
data = np.asarray(img2)

In [19]:
data

array([[[  0,   0,   0],
        [  0,   0, 224],
        [111,  64,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 224],
        [111,  64,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 224],
        [111,  64,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0, 224],
        [111,  64,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 224],
        [111,  64,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [20]:
data[50][50]

array([111,  64,   0], dtype=uint8)

In [21]:
data[50][50] = 255


ValueError: assignment destination is read-only

In [ ]:
img = np.array(img2)

In [ ]:
img[50][50] = (255, 0, 0)

In [ ]:
img[50][50]

In [ ]:
img3 = Image.fromarray(img, 'RGB')

In [ ]:
img3.show()

In [ ]:
img[49:51, 49:51] # row - col

In [ ]:
img = Image.open('img.png')

In [ ]:
data = np.asarray(img)

In [ ]:
data

In [ ]:
img2 = Image.open('img2.png')

In [ ]:
data2 = np.asarray(img2)

In [ ]:
data2

In [ ]:
# 24.05.2021
data3 = np.zeros((2, 2, 3))

In [ ]:
img3 = Image.fromarray(data3, 'RGB')

In [ ]:
img3.save("img3.png")


In [ ]:
data = np.asarray(img3)

In [ ]:
data

In [ ]:
img3.show()

In [ ]:
img = Image.open("img.png")

In [ ]:
data = np.asarray(img)

In [ ]:
data

In [ ]:
data.size

In [ ]:
data.shape

In [22]:
print(data)

[[[  0   0   0]
  [  0   0 224]
  [111  64   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0 224]
  [111  64   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0 224]
  [111  64   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[  0   0   0]
  [  0   0 224]
  [111  64   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0 224]
  [111  64   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]


In [23]:
print(img)

<PIL.Image.Image image mode=RGB size=200x100 at 0x23471FABF08>
